
language: c

compiler:
  - clang
  - gcc

os:
  - linux
  - osx

sudo: false

env:
  global:
    - BASE_OUTDIR=$TRAVIS_BUILD_DIR/out
    - BUILD=check
    - ENABLE_COVERAGE=no
    - ENABLE_VALGRIND=no

  matrix:
    - BUILD=distcheck MAKEJOBS=-j3
    - ENABLE_COVERAGE=yes
    - ENABLE_VALGRIND=yes

cache:
  apt: true

addons:
  apt:
    packages:
      - libssl-dev
      - libgmp-dev
      - libjansson-dev
      - libevent-dev
      - lcov
      - valgrind
      - libtool
      - libltdl-dev

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi

install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install jansson; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install libevent; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install argp-standalone; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install openssl; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "$ENABLE_COVERAGE" = "yes" ]; then brew install lcov; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "$ENABLE_VALGRIND" = "yes" ]; then brew install valgrind; fi
  - if [ "$ENABLE_COVERAGE" = "yes" ]; then gem install coveralls-lcov; fi

before_script:
  - if [ -n "$USE_SHELL" ]; then export CONFIG_SHELL="$USE_SHELL"; fi
  - test -n "$USE_SHELL" && eval '"$USE_SHELL" -c "./autogen.sh"' || ./autogen.sh

script:
  - OUTDIR=$BASE_OUTDIR/$TRAVIS_PULL_REQUEST/$TRAVIS_JOB_NUMBER-$HOST
  - PICOCOIN_CONFIG_ALL="--prefix=$TRAVIS_BUILD_DIR/depends/$HOST --bindir=$OUTDIR/bin --libdir=$OUTDIR/lib"
  - ./configure --cache-file=config.cache --enable-coverage=$ENABLE_COVERAGE --enable-valgrind=$ENABLE_VALGRIND $PICOCOIN_CONFIG_ALL $PICOCOIN_CONFIG || ( cat config.log && false)
  - make -s $MAKEJOBS $GOAL || ( echo "Build failure. Verbose build follows." && make $GOAL ; false )
  - export LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/depends/$HOST/lib
  - make $MAKEJOBS $BUILD

after_success:
  - if [ "$ENABLE_COVERAGE" = "yes" ]; then lcov --compat-libtool --directory . --capture --output-file coverage.info && coveralls-lcov coverage.info; fi